### ISSUE TITLE
please what happening !!

### ISSUE THREAD

**Issue by avatarvb** [20chix/course_Vue.js_Mongo_Express.js#1]
file : userListRoutes.js

'use strict';

module.exports = function(app){
  
  var userList = require('../controllers/userListController');

  app.route('/users')
     .get(userList.list_all_users)
     .post(userList.create_a_user);

     app.route('users/:userId')
        .get('userList.read_a_user');

};

=========== **Err** ===============================================

D:\Labo-Dev\api  (api@1.0.0)
λ node server
mongodb connection : ok
D:\Labo-Dev\api\node_modules\express\lib\router\route.js:202
        throw new Error(msg);
        ^

Error: Route.get() requires callback functions but got a [object String]
    at Route.(anonymous function) [as get] (D:\Labo-Dev\api\node_modules\express\lib\router\route.js:202:15)
    at module.exports (D:\Labo-Dev\api\routes\userListRoutes.js:11:10)
    at Object.<anonymous> (D:\Labo-Dev\api\server.js:16:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3

**Comment by 20chix** [comment]
Could you please explain in more details your problem. are you following the tutorial? From which section have you downloaded the test_server?

**Comment by avatarvb** [comment]
im not clonning the repo on github, i work wit your video on youtube : https://www.youtube.com/watch?v=wQ3Iarbyr3I&t=336s step by step
thnx for your attention

**Comment by 20chix** [comment]
maybe try to clone and compare the code from github. 

usually when you don't close mongoDB in the correct it throws this type of error. 

let me know :)

**Comment by avatarvb** [comment]
:) thnx for all i found the bug its too stupide 
        .get('userList.read_a_user');
i must  wirte it like this without " ' "
        .get(userList.read_a_user);

**Comment by 20chix** [comment]
👍 
 Please close issue
